### ISSUE TITLE
使用了之后，content内部的组件无法滑动

### ISSUE THREAD

**Issue by prohack** [hjl19911127/vue-drawer-layout#10]
rt，刚刚接触vue，不是很清楚原理，在屏幕上滑动的时候感觉像是被事件被提前接受并隔断了

**Comment by hjl19911127** [comment]
兄弟，你绑的啥事件，touch还是原生滚动？

**Comment by prohack** [comment]
最开始用的是这个：


```
<vue-drawer-layout
      ref="drawer"
      :drawer-width="800">
          <div class="drawer-content" slot="drawer">
            <!-- drawer-content -->
          </div>
          <div slot="content">
            <!-- main-content -->
          </div>
</vue-drawer-layout>
```

然后发现我content里面的组件无法滑动了，就换成

<vue-drawer-layout
      ref="drawer"
      :drawer-width="800"
      :enable="true"
      :animatable="true"
      :z-index="0"
      :drawable-distance="Math.floor(800/3)"
      :content-drawable="true"
      :backdrop="true"
      :backdrop-opacity-range="[0,0.4]"
      @slide-start="handleSlideStart"
      @slide-move="handleSlideMove"
      @slide-end="handleSlideEnd"
      @mask-click="handleMaskClick">
          <div class="drawer-content" slot="drawer">
            
          </div>
          <div slot="content">
            
          </div>
</vue-drawer-layout>


滑动的问题解决了，不过蒙版效果没有出来，滑动之后content布局全部向右移动并且消失了，界面上drawer之外的内容是黑色的..

**Comment by hjl19911127** [comment]
你是想要drawer盖在上面还是从content下面出来？

**Comment by prohack** [comment]
能否提供下那个移动QQ的源码给我参考一下呢，占用你的时间我感觉很不好意思...

**Comment by prohack** [comment]
盖在上面

**Comment by hjl19911127** [comment]
那你不能用:z-index="0"，这种是从下方拖出来的

**Comment by hjl19911127** [comment]
qq这种是从下方拖出来的

**Comment by hjl19911127** [comment]
http://share.codehuang.com/vue-drawer-layout  这里面的demo有看吗

**Comment by hjl19911127** [comment]
content里面的滑动容器的滑动事件，阻止冒泡

**Comment by prohack** [comment]
不好意思，没有注意到，我再去看看，谢啦

**Comment by hjl19911127** [comment]
最好看下具体是什么事件没触发哈，没事

**Comment by prohack** [comment]
对了，你的demo中没有给出css样式，drawer需要给他设置宽高吗

**Comment by hjl19911127** [comment]
drawer宽度是通过width可以控制，但是默认由容器的80%

**Comment by prohack** [comment]
我弄好了，虽然还是不太清楚原理，我自己再好好看看，谢谢

**Comment by gwsh1234** [comment]
> 我弄好了，虽然还是不太清楚原理，我自己再好好看看，谢谢

可以请教一下您是如何解决的吗
