### ISSUE TITLE
有蒙层的情况下点击主视图会调用handleSlideEnd方法

### ISSUE THREAD

**Issue by a-silent-guy** [hjl19911127/vue-drawer-layout#14]
点击主视图时会调用handleSlideEnd方法导致在handleSlideEnd里改变drawer显示和收起状态会出现问题

**Comment by hjl19911127** [comment]
有蒙层的情况下，应该点击不到主视图，大哥你能更详细的描述下吗

**Comment by a-silent-guy** [comment]
不好意思，哈哈，描述的不够详细，就是主视图上有一个按钮可以控制左边视图显示和收起，在左边视图收起情况下点击主视图任意位置都会调用handleSlideEnd这个方法，正常情况下，蒙层此时应该是不能被点击到的

**Comment by a-silent-guy** [comment]
经过测试蒙层点击方法确实没有被调用，但是handleSlideEnd这个方法会被调用

**Comment by hjl19911127** [comment]
最好能看下相关源码哈，方便提供吗

**Comment by a-silent-guy** [comment]
后面是源码地址，错误的地方敬请指正，初学Vue，多多包涵。https://github.com/coder-weed-Xu/Vue <https://github.com/coder-weed-Xu/Vue>
