### ISSUE TITLE
作者您好，有个问题询问下，我点击抽屉部分任何区域就会触发handleToggleDrawer，隐藏了抽屉页面

### ISSUE THREAD

**Issue by Jianping92** [hjl19911127/vue-drawer-layout#15]
主要是设置了抽屉页面的样式后点击任何区域都会隐藏抽屉页面。
代码是仿照的http://share.codehuang.com/vue-drawer-layout 
这个里面的Methods一项，具体代码如下：
template部分代码：
<vue-drawer-layout ref="drawerLayout">
      <div class="drawer" slot="drawer">
         <div class="drawerList" @click="handleToggleDrawer">
             <a @click="handleToggleDrawer">Hide Drawer</a>
         </div>
      </div>
      <div class="content" slot="content">
        </div>
      </div>
    </vue-drawer-layout>
JavaScript代码：
 methods: {
    handleToggleDrawer() {
      this.$refs.drawerLayout.toggle();
    }
}
css代码：
<style lang="stylus" scoped>
  .drawer
    .drawerList
      position: absolute
      overflow: hidden
      top: 0
      left: 0
      width: 95%
      height: 100%
      background: #ffffff
  .content
</style>

**Comment by Jianping92** [comment]
咦？代码显示不全了，我在这里再贴一下
template部分代码：
<vue-drawer-layout ref="drawerLayout">
      <div class="drawer" slot="drawer">
         <div class="drawerList" @click="handleToggleDrawer">
             <a @click="handleToggleDrawer">Hide Drawer</a>
         </div>
      </div>
      <div class="content" slot="content">
        </div>
      </div>
    </vue-drawer-layout>

**Comment by hjl19911127** [comment]
从代码上看，drawerList就是充满了整个抽屉的吧，还绑了handleToggleDrawer，那显然就会触发，大哥你确认下click的触发范围

**Comment by hjl19911127** [comment]
请问下还有问题吗？没问题我先关了哈
