### ISSUE TITLE
Option to swipe from bottom?

### ISSUE THREAD

**Issue by oscargglez** [hjl19911127/vue-drawer-layout#19]
It would be great if you could to create an option to set the swipe action from the bottom to get a drawer like maps on iOS. I taked a look to the code but for me it's a little bit complicated.

**Comment by hjl19911127** [comment]
Thanks for focusing our project.  The main difficulty is about how to control default scrolling and touching from bottom to above. I will estimate the idea soon.

**Comment by metinjakupi** [comment]
@hjl19911127 Any news about this ?

**Comment by hjl19911127** [comment]
use `drawer-position="bottom"` @metinjakupi
