### ISSUE TITLE
怎么设置变为右侧滑栏？

### ISSUE THREAD

**Issue by jjj2010** [hjl19911127/vue-drawer-layout#2]
如题

**Comment by hjl19911127** [comment]
右侧滑使用场景比较少见，我确认一下是否要加上这个特性，谢谢反馈

**Comment by hjl19911127** [comment]
用0.3.1版本，我增加了reverse属性，使其变为在右侧滑出，具体可以看例子[http://share.codehuang.com/vue-drawer-layout](http://share.codehuang.com/vue-drawer-layout)

**Comment by jjj2010** [comment]
有心了，多谢，我之前是在你代码上修改了下实现，现在增加了reverse，以后就方便了

**Comment by hjl19911127** [comment]
客气客气，共同学习进步
