### ISSUE TITLE
Open drawer like Android, on top of content

### ISSUE THREAD

**Issue by devWaleed** [hjl19911127/vue-drawer-layout#22]
Is it possible to open drawer on top of content? Like in Android instead of sliding the content to left/right?

**Comment by hjl19911127** [comment]
Not supported now. It will be considered soon. Thanks for your feedback.

**Comment by devWaleed** [comment]
@hjl19911127 ok I am using your Drawer in one of my mobile app with Cordova. Thanks for making this.

**Comment by hjl19911127** [comment]
@devWaleed upgrade to latest version and use `drawer-position="top"` prop
