### ISSUE TITLE
Add drawer 'isOpen' class

### ISSUE THREAD

**Issue by arcdelsol** [hjl19911127/vue-drawer-layout#23]
There needs to be classes or methods after opening and closing the drawer

**Comment by hjl19911127** [comment]
Does 'slide-end' event meet the needs ?

**Comment by arcdelsol** [comment]
'slide-end' doesn't determine whether the drawer is open or closed right?
Would be great if you can target the drawer state with css, 'open' or 'closed'

**Comment by hjl19911127** [comment]
slide-end event emit visible state of the drawer

**Comment by hjl19911127** [comment]
Adding the class may increase the risk of style conflict, so that's my opinion.Thanks for your understanding.
