### ISSUE TITLE
Style conflict with Bulma in Tabs

### ISSUE THREAD

**Issue by sowrensen** [hjl19911127/vue-drawer-layout#24]
The bottom border of the first item is still visible while it is selected. It only conflicts with the first item. I was working with Buefy which is based on Bulma. So I tested with both Bulma and Buefy tab component. See the attached image. 

![screenshot from 2019-02-17 12-18-26](https://user-images.githubusercontent.com/13097375/52909196-98287f80-32ae-11e9-940b-2adc8ea63e00.png)

**Comment by hjl19911127** [comment]
Hey buddy, i m confusing which style in my project conflict with your component, any further information? Thanks.

**Comment by sowrensen** [comment]
I would love to provide more help. But as I do not have a good front-end knowledge, I cannot specifically tell you which style is creating the malfunction. I just can say that as soon as I put a Tab component inside the drawer content, the style of the first item of the tab behaves weirdly. To be sure, I tried with two different project, and the outcome is same.

**Comment by hjl19911127** [comment]
Got any online demo?

**Comment by sowrensen** [comment]
Unfortunately no. Let's see if I can share one in codepen or something.

**Comment by sowrensen** [comment]
Buddy, I have added a demo on https://codesandbox.io/s/jnl5pjrx33. See if it can help.

**Comment by hjl19911127** [comment]
![image](https://user-images.githubusercontent.com/9312114/52928730-39313c00-337c-11e9-87de-0cb5f252bbfc.png)
Modify the class `content` to `section`

https://codesandbox.io/s/8znzwkp4ol

**Comment by sowrensen** [comment]
Thanks buddy. Appreciated. :smile:
