### ISSUE TITLE
Can't get it working with nuxt

### ISSUE THREAD

**Issue by regenrek** [hjl19911127/vue-drawer-layout#28]
Hey

thanks for this cool plugin. Do you have a example on how to use
this with nuxt please?

Thanks in advance!

**Comment by PaulHarrer** [comment]
@regenrek Unfortunately it does currently not support SSR, so you can use it with nuxt but only with client side rendering, or you would have to rewrite it to support SSR (should not be that much work).

For that you have to create a plugin and add it to the nuxt.config.js with the client parameter. For example you can do something like (of course you first have to install the npm package ;) ):

**plugins/vue-drawer-layout.js**
```
import Vue from 'vue'
import DrawerLayout from 'vue-drawer-layout'

Vue.use(DrawerLayout)
```

**nuxt.config.js**
```
...
plugins: [
    { src: '~/plugins/vue-drawer-layout', mode: 'client' },
  ],
...
```
