### ISSUE TITLE
Are we missing some css

### ISSUE THREAD

**Issue by Pixney-William** [hjl19911127/vue-drawer-layout#3]
Not sure if i am missing something. But it seems as if the content isn't scrollable. Are we missing come css for this?

**Comment by Pixney-William** [comment]
I had missed setting a class on content and adding the example styling:

```
    position: relative;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: #fa8787;
```

**Comment by focussing** [comment]
Hi @Pixney-William where did you add this class exactly? I cannot scroll the content of the drawer.

**Comment by Pixney-William** [comment]
Good question @focussing .. Can't remember what project i used it on. Ill keep it in the back of my head and if i remember ill get back to you :)
