### ISSUE TITLE
Option to enable or disable dragging

### ISSUE THREAD

**Issue by sowrensen** [hjl19911127/vue-drawer-layout#30]
Is there any way to switch the dragging? If not, can you please give a thought about it? Cause there are situations when I don't want the drawer to be revealed by dragging other than mouse click. It would be a great help.

**Comment by hjl19911127** [comment]
Hey buddy, it can be set `:enable="false"` to stop dragging and use `toggle` method to show and hide the drawer. I need to explain the prop `enable` more clearly. Thanks for your feedback, sincerely.

**Comment by sowrensen** [comment]
Oops... I thought it was for enabling or disabling the drawer. :rofl: 

Thanks anyway! You're the savior. :1st_place_medal:
