### ISSUE TITLE
Can't scroll elements inside the drawer

### ISSUE THREAD

**Issue by AlexandrDolzhikov** [hjl19911127/vue-drawer-layout#31]
Hello all)
I'm making this project - http://i.imgur.com/4raJvIx.png
My problem is - I can't scroll me filters insight drawer... I put filters and a graph in vue-drawer-layout component! But when I open the drawer - I can't scroll my filters! 
Please, help me, how can I fix it?

**Comment by focussing** [comment]
I added this to my <script> section
```
.drawer-layout .content-wrap {
	overflow: auto !important;
}
```

**Comment by focussing** [comment]
I think this should be updated to the component;  it should not interfere.

**Comment by hjl19911127** [comment]
or you can add style on root of drawer slot

**Comment by focussing** [comment]
@hjl19911127 sorry, can't get that to work; how?
