### ISSUE TITLE
this.$refs.drawerLayout  is undefined

### ISSUE THREAD

**Issue by superSuperwang** [hjl19911127/vue-drawer-layout#36]
我想用toggle()这个方法，但是显示未定义

**Comment by hjl19911127** [comment]
可以贴下模板吗？

**Comment by superSuperwang** [comment]
<template>
<div id="contain"> 
  <vue-drawer-layout ref="drawer" :drawer-width="800">
  <div class="drawer-content" slot="drawer">
    1234567
  </div>
  <div slot="content">
    
       
       <div class="mui-bar mui-bar-nav">
          <a class="mui-icon mui-action-menu mui-icon-bars mui-pull-left" @click="show"></a>
           <router-link class="tar" to="/mine">我的</router-link>
           <router-link class="tar" to="/find">发现</router-link>
           <router-link class="tar" to="/cloude">云村</router-link>
           <router-link class="tar" to="/video">视频</router-link>
           <router-link  to="/search" class="mui-icon  mui-icon-search"></router-link>
       </div>
       <router-view></router-view>
  </div>
</vue-drawer-layout> 
</div>

</template>
 
<script>
import DrawerLayout from 'vue-drawer-layout'
  export default{
    name:"APP",
    data(){
      return{

      }
    },
    methods:{
      show(){
        //this.$refs.drawerLayout.toggle();
        console.log(this.$refs.drawerLayout)
      }
    }
  }
</script>

**Comment by superSuperwang** [comment]
`<template>
<div id="contain"> 
  <vue-drawer-layout ref="drawer" :drawer-width="800">
  <div class="drawer-content" slot="drawer">
    1234567
  </div>
  <div slot="content">
    
       
       <div class="mui-bar mui-bar-nav">
          <a class="mui-icon mui-action-menu mui-icon-bars mui-pull-left" @click="show"></a>
           <router-link class="tar" to="/mine">我的</router-link>
           <router-link class="tar" to="/find">发现</router-link>
           <router-link class="tar" to="/cloude">云村</router-link>
           <router-link class="tar" to="/video">视频</router-link>
           <router-link  to="/search" class="mui-icon  mui-icon-search"></router-link>
       </div>
       <router-view></router-view>
  </div>
</vue-drawer-layout> 
</div>

</template>
 
<script>
import DrawerLayout from 'vue-drawer-layout'
  export default{
    name:"APP",
    data(){
      return{

      }
    },
    methods:{
      show(){
        //this.$refs.drawerLayout.toggle();
        console.log(this.$refs.drawerLayout)
      }
    }
  }
</script>`

**Comment by hjl19911127** [comment]
ref 定义在哪里

**Comment by superSuperwang** [comment]
<vue-drawer-layout ref="drawerLayout" :drawer-width="800">
是这个吗，还是说要另外定义

**Comment by superSuperwang** [comment]
<vue-drawer-layout ref="drawer" :drawer-width="800">

**Comment by superSuperwang** [comment]
`<vue-drawer-layout ref="drawer" :drawer-width="800">`

**Comment by superSuperwang** [comment]
`<vue-drawer-layout ref="drawerLayout" :drawer-width="800">`

**Comment by hjl19911127** [comment]
那ref就是drawer呢，this.$refs.drawer，建议先看看vue的语法，哥们

**Comment by hjl19911127** [comment]
ref="drawerLayout"

**Comment by superSuperwang** [comment]
我刚学一个星期不是很熟悉

**Comment by superSuperwang** [comment]
解决了谢谢了

**Comment by hjl19911127** [comment]
不客气，建议先多看看`vue`的使用
