### ISSUE TITLE
该组件导致无法页面滚动？

### ISSUE THREAD

**Issue by himself65** [hjl19911127/vue-drawer-layout#4]
在未使用您的框架下
``` JavaScript
<template>
  <div id="drawer">
    <navbar @childEvent="handleToggleDrawer"></navbar>
    <slot></slot>
    <toolbar></toolbar>
  </div>
</template>
```

该可以将长页面拉到最底层

而在使用您的框架时
``` JavaScript
<vue-drawer-layout ref="drawerLayout">
    <div class="drawer" slot="drawer">
      <navbar-list></navbar-list>
    </div>
    <div class="content" slot="content">
      <navbar @childEvent="handleToggleDrawer"></navbar>
      <slot></slot>
      <toolbar></toolbar>
    </div>
</vue-drawer-layout>
```

在content元素过长时候无法进行页面滚动，而我并没有办法解决这个问题

**Comment by hjl19911127** [comment]
您需要借助样式来滚动
```css
.content{
    overflow: auto;
}
```

**Comment by himself65** [comment]
@hjl19911127  我尝试过这样，但是并没有什么卵用

**Comment by hjl19911127** [comment]
该容器有高度吗？

**Comment by himself65** [comment]
@hjl19911127  我觉得是不是嵌套了子组件的问题？

**Comment by hjl19911127** [comment]
![image](https://user-images.githubusercontent.com/9312114/38456397-0a915524-3ab7-11e8-8d24-5436702629d1.png)
如图，容器需要有高度和overflow，才有滚动，这个跟组件是没关系的，是css的问题

**Comment by himself65** [comment]
@hjl19911127  您可以看我写的https://github.com/Himself65/ChartRoom 其中的https://github.com/Himself65/ChartRoom/blob/master/src/router/Home.vue

**Comment by hjl19911127** [comment]
![image](https://user-images.githubusercontent.com/9312114/38463682-bee9a794-3b32-11e8-82f0-69f9a11e5a17.png)
如图，您需要在scrollarea中加这个样式

**Comment by hjl19911127** [comment]
@Himself65 建议关注下css滚动条件

**Comment by himself65** [comment]
@hjl19911127 已经解决了，是我才疏学浅了:P

**Comment by hjl19911127** [comment]
共同进步，加油！ @Himself65
