### ISSUE TITLE
侧滑栏的内容会显示在主页面的底下了  bug吗？ 怎么搞？

### ISSUE THREAD

**Issue by hzq-up** [hjl19911127/vue-drawer-layout#42]
![image](https://user-images.githubusercontent.com/56748572/99150572-83ba2680-26d0-11eb-984e-f2dba645b6b0.png)
侧滑栏的内容怎么会显示到主页面的内容低下了，

**Comment by hjl19911127** [comment]
可以通过`zIndex`属性提升drawer的层级
