### ISSUE TITLE
你文档上的调用toggle方法写错了

### ISSUE THREAD

**Issue by HuPengUpUp** [hjl19911127/vue-drawer-layout#7]
你文档上的调用toggle方法写错了,应该是this.$refs.drawer.toggle()调用,还有复制你的代码全是中文标点,头大啊!!!
不过还是谢谢你

**Comment by hjl19911127** [comment]
![image](https://user-images.githubusercontent.com/9312114/42441176-3b5d050a-839a-11e8-8020-ec11c3cfe909.png)
哥们，问下我是哪里文档写的有问题哈，我好像没有找到，还有哪个地方复制都是中文标点额？麻烦了，多谢

**Comment by hjl19911127** [comment]
Demo在这里哈，http://share.codehuang.com/vue-drawer-layout

**Comment by hjl19911127** [comment]
兄弟你还有啥问题不，没问题我先关了
