### ISSUE TITLE
content里面的list无法滑动

### ISSUE THREAD

**Issue by luo578904042** [hjl19911127/vue-drawer-layout#8]
<vue-drawer-layout
      ref="drawer"
      :drawer-width="800">
      <div class="drawer-content" slot="drawer">
          <home-navigationbar></home-navigationbar>
      </div>
      <div slot="content">
        <router-view ></router-view>
      </div>
    </vue-drawer-layout>

**Comment by luo578904042** [comment]
每次滑动content里面的list，都是触发drawer-wrap的滑动事件

**Comment by hjl19911127** [comment]
是横向滑动还是纵向滑动？

**Comment by hjl19911127** [comment]
兄弟还有问题吗，如果没有问题我先关了哈
