### ISSUE TITLE
滑动问题

### ISSUE THREAD

**Issue by fengdou1** [hjl19911127/vue-drawer-layout#9]
微信内置浏览器 content内容上下滑动在iphone上不能滑动，Android没问题，这个问题不兼容么，有没有什么好的解决方法呢？

**Comment by hjl19911127** [comment]
滚动条能出来吗，你有没有在内部自己套一个滚动的容器

**Comment by fengdou1** [comment]
有滚动条 滑动很僵硬

**Comment by fengdou1** [comment]
解决了 没想到作者有问题这么及时回复  用了这个 -webkit-overflow-scrolling:touch;

**Comment by hjl19911127** [comment]
今天事情少刚好看到邮件，兄弟给力了
